import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"前端文章","description":"","frontmatter":{},"headers":[{"level":2,"title":"前端体系梳理","slug":"前端体系梳理","link":"#前端体系梳理","children":[]},{"level":2,"title":"浏览器","slug":"浏览器","link":"#浏览器","children":[]},{"level":2,"title":"HTML && CSS","slug":"html-css","link":"#html-css","children":[]},{"level":2,"title":"JavaScript","slug":"javascript","link":"#javascript","children":[]},{"level":2,"title":"Vue","slug":"vue","link":"#vue","children":[]},{"level":2,"title":"计算机网络","slug":"计算机网络","link":"#计算机网络","children":[]}],"relativePath":"resources/website/fe_blogs.md","lastUpdated":1700547143000}');
const _sfc_main = { name: "resources/website/fe_blogs.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="前端文章" tabindex="-1">前端文章 <a class="header-anchor" href="#前端文章" aria-hidden="true">#</a></h1><h2 id="前端体系梳理" tabindex="-1">前端体系梳理 <a class="header-anchor" href="#前端体系梳理" aria-hidden="true">#</a></h2><p><a href="https://segmentfault.com/a/1190000013662126" link="card" target="_blank" rel="noreferrer">从输入 URL 到页面加载的过程？如何由一道题完善自己的前端知识体系！</a></p><h2 id="浏览器" tabindex="-1">浏览器 <a class="header-anchor" href="#浏览器" aria-hidden="true">#</a></h2><p><a href="https://www.cnblogs.com/chenyoumei/p/9156849.html" link="card" target="_blank" rel="noreferrer">浏览器渲染页面的原理和流程</a></p><p><a href="https://segmentfault.com/a/1190000014383214" link="card" target="_blank" rel="noreferrer">V8 引擎垃圾回收</a></p><h2 id="html-css" tabindex="-1">HTML &amp;&amp; CSS <a class="header-anchor" href="#html-css" aria-hidden="true">#</a></h2><p><a href="https://www.jianshu.com/p/f5ffd5e014a9" link="card" target="_blank" rel="noreferrer">script 标签 async 和 defer 区别</a><a href="https://www.jianshu.com/p/9a463d50e441" link="card" target="_blank" rel="noreferrer">CSS 绘制三角形</a></p><h2 id="javascript" tabindex="-1">JavaScript <a class="header-anchor" href="#javascript" aria-hidden="true">#</a></h2><p><a href="https://www.cnblogs.com/wangfupeng1988/p/3977924.html" link="card" target="_blank" rel="noreferrer">深入理解 javascript 原型和闭包</a><a href="https://zhuanlan.zhihu.com/p/26229293" link="card" target="_blank" rel="noreferrer">深入浅出 Javascript 事件循环机制(上){link=card}</a><a href="https://zhuanlan.zhihu.com/p/46068171" link="card" target="_blank" rel="noreferrer">深入理解 JavaScript 的事件循环</a><a href="https://zhuanlan.zhihu.com/p/72507900" link="card" target="_blank" rel="noreferrer">如何解释 Event Loop 面试官才满意？</a><a href="https://www.cnblogs.com/lhb25/archive/2011/09/06/javascript-scope-chain.html" link="card" target="_blank" rel="noreferrer">理解作用域和作用域链</a></p><h2 id="vue" tabindex="-1">Vue <a class="header-anchor" href="#vue" aria-hidden="true">#</a></h2><p><a href="https://www.cnblogs.com/canfoo/p/6891868.html" link="card" target="_blank" rel="noreferrer">Vue 双向绑定原理及实现</a><a href="https://blog.csdn.net/w993263495/article/details/85030839" link="card" target="_blank" rel="noreferrer">Vuejs 如何实现双向绑定</a><a href="https://segmentfault.com/a/1190000006599500" link="card" target="_blank" rel="noreferrer">剖析 Vue 原理&amp;实现双向绑定 MVVM</a><a href="https://www.cnblogs.com/lgt-hello-world/p/12620073.html" link="card" target="_blank" rel="noreferrer">vue 生命周期</a><a href="https://www.jianshu.com/p/7af8554d8f08" link="card" target="_blank" rel="noreferrer">v-if 与 v-show 的区别</a></p><h2 id="计算机网络" tabindex="-1">计算机网络 <a class="header-anchor" href="#计算机网络" aria-hidden="true">#</a></h2><p><a href="https://www.pianshen.com/article/68431265749/" link="card" target="_blank" rel="noreferrer">TCP 三次握手最后一次失败怎么办</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("resources/website/fe_blogs.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const fe_blogs = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  fe_blogs as default
};
